title = "Alpaca Sample Driver (Cam)"

[network]
ip_address = ''             # Any address
port = 5555

[server]
location = 'Anywhere on Earth'  # Anything you want here
verbose_driver_exceptions = true

[device]
cti_path = 'C:\Program Files\SVS-VISTEK GmbH\SVCam Kit\TLUsb\bin\sv_u3v_tl_x64.cti'
PixelFormat = 'Mono12Packed'

[logging]
log_level = 'INFO'
log_to_stdout = false
max_size_mb = 5
num_keep_logs = 10
